/* The following code was generated by JFlex 1.6.1 */

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright (C) 2000 Gerwin Klein <lsf@jflex.de>                          *
 * All rights reserved.                                                    *
 *                                                                         *
 * Thanks to Larry Bell and Bob Jamison for suggestions and comments.      *
 *                                                                         *
 * License: BSD                                                            *
 *                                                                         *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
import java.util.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\10\0\1\55\1\6\1\5\1\11\1\11\1\10\22\0\1\6\1\54"+
    "\1\0\1\7\2\0\1\22\1\0\1\44\1\45\1\52\1\52\1\21"+
    "\1\50\1\2\1\52\12\1\1\0\1\46\1\47\1\53\1\51\2\0"+
    "\32\3\1\23\1\0\1\24\1\0\1\4\1\0\1\17\1\14\1\35"+
    "\1\40\1\16\1\26\1\3\1\43\1\25\1\3\1\20\1\27\1\3"+
    "\1\32\1\37\1\31\1\3\1\15\1\30\1\33\1\34\1\36\1\42"+
    "\2\3\1\41\1\12\1\0\1\13\7\0\1\11\u1fa2\0\1\11\1\11"+
    "\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\1\3\1\4\1\5\1\6\1\7\1\2"+
    "\1\10\1\11\4\5\1\1\1\12\1\13\1\14\12\5"+
    "\1\15\1\16\1\17\1\20\1\21\1\20\1\21\1\20"+
    "\1\2\1\22\1\0\1\23\1\0\5\5\1\24\15\5"+
    "\1\21\1\5\1\25\1\26\1\27\1\0\4\5\1\30"+
    "\6\5\1\31\2\5\1\32\2\5\1\33\1\5\1\34"+
    "\1\5\1\35\1\5\1\36\1\37\2\5\1\40\1\5"+
    "\1\41\1\5\1\42\1\5\1\43\1\5\1\44\1\5"+
    "\1\45\1\46\1\47\2\5\1\50";

  private static int [] zzUnpackAction() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\56\0\134\0\56\0\212\0\56\0\270\0\346"+
    "\0\56\0\56\0\u0114\0\u0142\0\u0170\0\u019e\0\56\0\56"+
    "\0\56\0\56\0\u01cc\0\u01fa\0\u0228\0\u0256\0\u0284\0\u02b2"+
    "\0\u02e0\0\u030e\0\u033c\0\u036a\0\56\0\56\0\56\0\u0398"+
    "\0\u03c6\0\u03f4\0\56\0\56\0\u03f4\0\56\0\u0422\0\u0450"+
    "\0\u047e\0\u04ac\0\u04da\0\u0508\0\u0536\0\u0564\0\212\0\u0592"+
    "\0\u05c0\0\u05ee\0\u061c\0\u064a\0\u0678\0\u06a6\0\u06d4\0\u0702"+
    "\0\u0730\0\u075e\0\u078c\0\u07ba\0\212\0\u07e8\0\56\0\56"+
    "\0\u0422\0\u0816\0\u0844\0\u0872\0\u08a0\0\u08ce\0\212\0\u08fc"+
    "\0\u092a\0\u0958\0\u0986\0\u09b4\0\u09e2\0\212\0\u0a10\0\u0a3e"+
    "\0\212\0\u0a6c\0\u0a9a\0\u047e\0\u0ac8\0\212\0\u0af6\0\212"+
    "\0\u0b24\0\212\0\212\0\u0b52\0\u0b80\0\212\0\u0bae\0\212"+
    "\0\u0bdc\0\212\0\u0c0a\0\212\0\u0c38\0\212\0\u0c66\0\212"+
    "\0\212\0\212\0\u0c94\0\u0cc2\0\212";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\2\1\6\1\7\1\10"+
    "\1\7\1\2\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\5\1\17\1\20\1\21\1\22\1\23\1\24\1\5"+
    "\1\25\1\26\1\27\1\30\1\5\1\31\1\32\1\33"+
    "\2\5\1\34\1\5\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\57\0\1\3\1\47"+
    "\54\0\1\5\1\0\2\5\7\0\5\5\4\0\17\5"+
    "\20\0\1\7\1\0\1\7\54\0\1\50\2\0\1\51"+
    "\44\0\1\5\1\0\2\5\7\0\1\5\1\52\3\5"+
    "\4\0\12\5\1\53\4\5\13\0\1\5\1\0\2\5"+
    "\7\0\2\5\1\54\2\5\4\0\17\5\13\0\1\5"+
    "\1\0\2\5\7\0\5\5\4\0\2\5\1\55\14\5"+
    "\13\0\1\5\1\0\2\5\7\0\5\5\4\0\5\5"+
    "\1\56\11\5\13\0\1\5\1\0\2\5\7\0\5\5"+
    "\4\0\1\5\1\57\3\5\1\60\11\5\13\0\1\5"+
    "\1\0\2\5\7\0\3\5\1\61\1\5\4\0\2\5"+
    "\1\62\4\5\1\63\7\5\13\0\1\5\1\0\2\5"+
    "\7\0\5\5\4\0\1\64\5\5\1\65\10\5\13\0"+
    "\1\5\1\0\2\5\7\0\1\5\1\66\3\5\4\0"+
    "\17\5\13\0\1\5\1\0\2\5\7\0\2\5\1\67"+
    "\2\5\4\0\12\5\1\70\4\5\13\0\1\5\1\0"+
    "\2\5\7\0\1\5\1\71\3\5\4\0\17\5\13\0"+
    "\1\5\1\0\2\5\7\0\5\5\4\0\12\5\1\72"+
    "\4\5\13\0\1\5\1\0\2\5\7\0\3\5\1\73"+
    "\1\5\4\0\12\5\1\74\4\5\13\0\1\5\1\0"+
    "\2\5\7\0\1\5\1\75\3\5\4\0\17\5\13\0"+
    "\1\5\1\0\2\5\7\0\5\5\4\0\16\5\1\76"+
    "\62\0\1\77\2\0\1\44\53\0\1\100\57\0\1\44"+
    "\3\0\1\101\54\0\5\50\1\0\2\50\2\0\44\50"+
    "\10\51\2\0\1\51\1\102\42\51\1\0\1\5\1\0"+
    "\2\5\7\0\2\5\1\103\2\5\4\0\17\5\13\0"+
    "\1\5\1\0\2\5\7\0\5\5\4\0\12\5\1\104"+
    "\4\5\13\0\1\5\1\0\2\5\7\0\5\5\4\0"+
    "\6\5\1\105\10\5\13\0\1\5\1\0\2\5\7\0"+
    "\5\5\4\0\3\5\1\106\13\5\13\0\1\5\1\0"+
    "\2\5\7\0\5\5\4\0\13\5\1\75\3\5\13\0"+
    "\1\5\1\0\2\5\7\0\5\5\4\0\6\5\1\107"+
    "\10\5\13\0\1\5\1\0\2\5\7\0\5\5\4\0"+
    "\2\5\1\110\14\5\13\0\1\5\1\0\2\5\7\0"+
    "\5\5\4\0\12\5\1\111\4\5\13\0\1\5\1\0"+
    "\2\5\7\0\5\5\4\0\5\5\1\112\11\5\13\0"+
    "\1\5\1\0\2\5\7\0\5\5\4\0\14\5\1\113"+
    "\2\5\13\0\1\5\1\0\2\5\7\0\1\5\1\114"+
    "\3\5\4\0\17\5\13\0\1\5\1\0\2\5\7\0"+
    "\5\5\4\0\1\115\16\5\13\0\1\5\1\0\2\5"+
    "\7\0\5\5\4\0\15\5\1\116\1\5\13\0\1\5"+
    "\1\0\2\5\7\0\5\5\4\0\6\5\1\75\10\5"+
    "\13\0\1\5\1\0\2\5\7\0\5\5\4\0\7\5"+
    "\1\117\7\5\13\0\1\5\1\0\2\5\7\0\5\5"+
    "\4\0\5\5\1\120\11\5\13\0\1\5\1\0\2\5"+
    "\7\0\1\5\1\121\3\5\4\0\17\5\13\0\1\5"+
    "\1\0\2\5\7\0\5\5\4\0\1\122\16\5\13\0"+
    "\1\5\1\0\2\5\7\0\5\5\4\0\1\123\16\5"+
    "\12\0\7\51\1\124\2\0\1\51\1\102\42\51\1\0"+
    "\1\5\1\0\2\5\7\0\3\5\1\125\1\5\4\0"+
    "\17\5\13\0\1\5\1\0\2\5\7\0\5\5\4\0"+
    "\2\5\1\126\14\5\13\0\1\5\1\0\2\5\7\0"+
    "\5\5\4\0\7\5\1\127\7\5\13\0\1\5\1\0"+
    "\2\5\7\0\2\5\1\130\2\5\4\0\17\5\13\0"+
    "\1\5\1\0\2\5\7\0\5\5\4\0\3\5\1\117"+
    "\13\5\13\0\1\5\1\0\2\5\7\0\3\5\1\131"+
    "\1\5\4\0\17\5\13\0\1\5\1\0\2\5\7\0"+
    "\5\5\4\0\10\5\1\132\6\5\13\0\1\5\1\0"+
    "\2\5\7\0\2\5\1\133\2\5\4\0\17\5\13\0"+
    "\1\5\1\0\2\5\7\0\5\5\4\0\7\5\1\134"+
    "\7\5\13\0\1\5\1\0\2\5\7\0\5\5\4\0"+
    "\5\5\1\135\11\5\13\0\1\5\1\0\2\5\7\0"+
    "\2\5\1\136\2\5\4\0\17\5\13\0\1\5\1\0"+
    "\2\5\7\0\5\5\4\0\6\5\1\137\10\5\13\0"+
    "\1\5\1\0\2\5\7\0\5\5\4\0\13\5\1\140"+
    "\3\5\13\0\1\5\1\0\2\5\7\0\5\5\4\0"+
    "\2\5\1\141\14\5\13\0\1\5\1\0\2\5\7\0"+
    "\4\5\1\142\4\0\17\5\13\0\1\5\1\0\2\5"+
    "\7\0\1\5\1\143\3\5\4\0\17\5\13\0\1\5"+
    "\1\0\2\5\7\0\5\5\4\0\6\5\1\144\10\5"+
    "\13\0\1\5\1\0\2\5\7\0\5\5\4\0\10\5"+
    "\1\145\6\5\13\0\1\5\1\0\2\5\7\0\5\5"+
    "\4\0\6\5\1\146\10\5\13\0\1\5\1\0\2\5"+
    "\7\0\5\5\4\0\1\147\16\5\13\0\1\5\1\0"+
    "\2\5\7\0\2\5\1\150\2\5\4\0\17\5\13\0"+
    "\1\5\1\0\2\5\7\0\5\5\4\0\5\5\1\151"+
    "\11\5\13\0\1\5\1\0\2\5\7\0\5\5\4\0"+
    "\6\5\1\152\10\5\13\0\1\5\1\0\2\5\7\0"+
    "\5\5\4\0\5\5\1\153\11\5\13\0\1\5\1\0"+
    "\2\5\7\0\5\5\4\0\7\5\1\154\7\5\13\0"+
    "\1\5\1\0\2\5\7\0\2\5\1\155\2\5\4\0"+
    "\17\5\12\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3312];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\1\1\1\11\1\1\1\11\2\1\2\11"+
    "\4\1\4\11\12\1\3\11\3\1\2\11\1\1\1\11"+
    "\1\0\1\1\1\0\25\1\2\11\1\1\1\0\53\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */

  public Parser   parser;
  public int      lineno;
  public int      column;
  public int      counter=0;

  public Lexer(java.io.Reader r, Parser parser) {
    this(r);
    this.parser = parser;
    this.lineno = 1;
    this.column = 1;

  }
  HashMap<String, Integer> symbolTable = new HashMap<>();




  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 174) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return 0; }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { parser.yylval = new ParserVal((Object)yytext()); return Parser.COMMA   ;
            }
          case 41: break;
          case 2: 
            { System.err.println("Error: unexpected character '"+yytext()+"'"); return -1;
            }
          case 42: break;
          case 3: 
            { parser.yylval = new ParserVal((Object)yytext()); return Parser.INT_LIT ;
            }
          case 43: break;
          case 4: 
            { parser.yylval = new ParserVal((Object)yytext()); return Parser.DOT   ;
            }
          case 44: break;
          case 5: 
            { parser.yylval = new ParserVal((Object)yytext());
                                      if(!symbolTable.containsKey(yytext())){
                                          symbolTable.put(yytext(),counter);
                                          System.out.print(String.format("<<new symbol table entity [%d, %s]>>", counter, yytext()));
                                          counter++;
                                      }
                                        return Parser.IDENT   ;
            }
          case 45: break;
          case 6: 
            { String lexeme=yytext();
          System.out.print(yytext());
          lineno++;
          column=1;/* line skip */
            }
          case 46: break;
          case 7: 
            { if (yytext().equals("    ")){
              column+=4;
          }
          else if (yytext().equals("\t")){
                        column+=4;
                    }
          else{
              for(int i=0; i<yytext().length();i++){
                  if (yytext().charAt(i)==' '){
                      column++;
                  }
              }
          }
          System.out.print(yytext());
          /* white skip */
            }
          case 47: break;
          case 8: 
            { parser.yylval = new ParserVal((Object)yytext()); return Parser.BEGIN   ;
            }
          case 48: break;
          case 9: 
            { parser.yylval = new ParserVal((Object)yytext()); return Parser.END     ;
            }
          case 49: break;
          case 10: 
            { parser.yylval = new ParserVal((Object)yytext()); return Parser.ADDR   ;
            }
          case 50: break;
          case 11: 
            { parser.yylval = new ParserVal((Object)yytext()); return Parser.LBRACKET   ;
            }
          case 51: break;
          case 12: 
            { parser.yylval = new ParserVal((Object)yytext()); return Parser.RBRACKET   ;
            }
          case 52: break;
          case 13: 
            { parser.yylval = new ParserVal((Object)yytext()); return Parser.LPAREN  ;
            }
          case 53: break;
          case 14: 
            { parser.yylval = new ParserVal((Object)yytext()); return Parser.RPAREN  ;
            }
          case 54: break;
          case 15: 
            { parser.yylval = new ParserVal((Object)yytext()); return Parser.SEMI    ;
            }
          case 55: break;
          case 16: 
            { parser.yylval = new ParserVal((Object)yytext()); return Parser.RELOP   ;
            }
          case 56: break;
          case 17: 
            { parser.yylval = new ParserVal((Object)yytext()); return Parser.OP      ;
            }
          case 57: break;
          case 18: 
            { System.err.println("Sorry, backspace doesn't work");
            }
          case 58: break;
          case 19: 
            { String lexeme=yytext();
          System.out.print(yytext()); /* linwecomm skip */
            }
          case 59: break;
          case 20: 
            { parser.yylval = new ParserVal((Object)yytext()); return Parser.IF   ;
            }
          case 60: break;
          case 21: 
            { parser.yylval = new ParserVal((Object)yytext()); return Parser.ASSIGN  ;
            }
          case 61: break;
          case 22: 
            { parser.yylval = new ParserVal((Object)yytext()); return Parser.FUNCRET ;
            }
          case 62: break;
          case 23: 
            { parser.yylval = new ParserVal((Object)yytext()); return Parser.FLOAT_LIT   ;
            }
          case 63: break;
          case 24: 
            { parser.yylval = new ParserVal((Object)yytext()); return Parser.INT     ;
            }
          case 64: break;
          case 25: 
            { parser.yylval = new ParserVal((Object)yytext()); return Parser.NEW    ;
            }
          case 65: break;
          case 26: 
            { parser.yylval = new ParserVal((Object)yytext()); return Parser.VAR    ;
            }
          case 66: break;
          case 27: 
            { String lexeme=yytext();
          System.out.print(yytext());/* blk skip */
            }
          case 67: break;
          case 28: 
            { parser.yylval = new ParserVal((Object)yytext()); return Parser.BOOL    ;
            }
          case 68: break;
          case 29: 
            { parser.yylval = new ParserVal((Object)yytext()); return Parser.ELSE   ;
            }
          case 69: break;
          case 30: 
            { parser.yylval = new ParserVal((Object)yytext()); return Parser.FUNC    ;
            }
          case 70: break;
          case 31: 
            { parser.yylval = new ParserVal((Object)yytext()); return Parser.SIZE    ;
            }
          case 71: break;
          case 32: 
            { parser.yylval = new ParserVal((Object)yytext()); return Parser.BOOL_LIT   ;
            }
          case 72: break;
          case 33: 
            { parser.yylval = new ParserVal((Object)yytext()); return Parser.VOID    ;
            }
          case 73: break;
          case 34: 
            { parser.yylval = new ParserVal((Object)yytext()); return Parser.BREAK   ;
            }
          case 74: break;
          case 35: 
            { parser.yylval = new ParserVal((Object)yytext()); return Parser.FLOAT    ;
            }
          case 75: break;
          case 36: 
            { parser.yylval = new ParserVal((Object)yytext()); return Parser.PRINT   ;
            }
          case 76: break;
          case 37: 
            { parser.yylval = new ParserVal((Object)yytext()); return Parser.WHILE    ;
            }
          case 77: break;
          case 38: 
            { parser.yylval = new ParserVal((Object)yytext()); return Parser.RETURN    ;
            }
          case 78: break;
          case 39: 
            { parser.yylval = new ParserVal((Object)yytext()); return Parser.STRUCT    ;
            }
          case 79: break;
          case 40: 
            { parser.yylval = new ParserVal((Object)yytext()); return Parser.CONTINUE    ;
            }
          case 80: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
